const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Behaviors.bound,
		C3.Behaviors.DragnDrop,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Follow,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Follow.Cnds.IsFollowingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAngle
	];
};
self.C3_JsPropNameTable = [
	{Твёрдый: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{УничтожениеВнеМакета: 0},
	{ОграничитьСценой: 0},
	{игрок: 0},
	{Перетаскивание: 0},
	{железная_руда: 0},
	{алмазная_руда: 0},
	{золотая_руда: 0},
	{изумрудная_руда: 0},
	{медная_руда: 0},
	{редстоуновая_руда: 0},
	{Якорь: 0},
	{жизнь: 0},
	{песок: 0},
	{песчаник: 0},
	{трава: 0},
	{вода: 0},
	{земля: 0},
	{Клавиатура: 0},
	{тростник: 0},
	{кактус: 0},
	{житель: 0},
	{житель2: 0},
	{камень: 0},
	{ТайловыйФон: 0},
	{дерево: 0},
	{листва: 0},
	{Мышь: 0},
	{Аудио: 0},
	{мох: 0},
	{обсидиан: 0},
	{ТайловыйФон2: 0},
	{бедрок: 0},
	{лава: 0},
	{сундук: 0},
	{ДвижениеПоКлеткам: 0},
	{свинья: 0},
	{Незерак: 0},
	{СледоватьЗа: 0},
	{зомби: 0},
	{Спрайт57: 0},
	{верстак: 0},
	{ТайловыйФон3: 0},
	{Незеритовая_руда: 0},
	{Спрайт61: 0},
	{кварц: 0},
	{Спрайт: 0}
];

self.InstanceType = {
	игрок: class extends self.ISpriteInstance {},
	железная_руда: class extends self.ISpriteInstance {},
	алмазная_руда: class extends self.ISpriteInstance {},
	золотая_руда: class extends self.ISpriteInstance {},
	изумрудная_руда: class extends self.ISpriteInstance {},
	медная_руда: class extends self.ISpriteInstance {},
	редстоуновая_руда: class extends self.ISpriteInstance {},
	жизнь: class extends self.ITiledBackgroundInstance {},
	песок: class extends self.ISpriteInstance {},
	песчаник: class extends self.ISpriteInstance {},
	трава: class extends self.ISpriteInstance {},
	вода: class extends self.ISpriteInstance {},
	земля: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	тростник: class extends self.ISpriteInstance {},
	кактус: class extends self.ISpriteInstance {},
	житель: class extends self.ISpriteInstance {},
	житель2: class extends self.ISpriteInstance {},
	камень: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	дерево: class extends self.ISpriteInstance {},
	листва: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Аудио: class extends self.IInstance {},
	мох: class extends self.ISpriteInstance {},
	обсидиан: class extends self.ISpriteInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	бедрок: class extends self.ISpriteInstance {},
	лава: class extends self.ISpriteInstance {},
	сундук: class extends self.ISpriteInstance {},
	свинья: class extends self.ISpriteInstance {},
	Незерак: class extends self.ISpriteInstance {},
	зомби: class extends self.ISpriteInstance {},
	Спрайт57: class extends self.ISpriteInstance {},
	верстак: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	Незеритовая_руда: class extends self.ISpriteInstance {},
	Спрайт61: class extends self.ISpriteInstance {},
	кварц: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {}
}